SELECT * FROM frt_pre_Fat

SELECT * FROM FRT_FTA

rollback

select * from frt_vol_not_fis
 SELECT *
FROM  FRT_FTA
WHERE EXTRACT(YEAR FROM dat_ems) BETWEEN '2011' AND '2012'; 

DELETE
FROM  frt_pre_Fat
WHERE EXTRACT(YEAR FROM DAT_EMS) BETWEEN '2011' AND '2012'; 

 SELECT *
FROM  FRT_PRE_FAT_RCT_DOC_TRP
WHERE EXTRACT(YEAR FROM dat_ems) BETWEEN '2019' AND '2020'; 

DELETE
FROM  FRT_PRE_FAT_RCT_DOC_TRP
WHERE EXTRACT(YEAR FROM DAT_EMS) BETWEEN '2011' AND '2012'; 

WHERE DAT_EMS = 5-8-2012
WHERE NRO_PRE_FAT = 8



DELETE FROM FRT_PRE_FAT_RCT_DOC_TRP
DAT_EMS = 
WHERE NRO_PRE_FAT = 108
OR NRO_PRE_FAT = 109
OR NRO_PRE_FAT = 110
OR NRO_PRE_FAT = 119
OR NRO_PRE_FAT = 131
OR NRO_PRE_FAT = 132
OR NRO_PRE_FAT = 133
OR NRO_PRE_FAT = 141
OR NRO_PRE_FAT = 142
OR NRO_PRE_FAT = 147
OR NRO_PRE_FAT = 102
OR NRO_PRE_FAT = 103
OR NRO_PRE_FAT = 111
OR NRO_PRE_FAT = 113
OR NRO_PRE_FAT = 114
OR NRO_PRE_FAT = 117
OR NRO_PRE_FAT = 118
OR NRO_PRE_FAT = 123
OR NRO_PRE_FAT = 124
OR NRO_PRE_FAT = 125
OR NRO_PRE_FAT = 126
OR NRO_PRE_FAT = 136
OR NRO_PRE_FAT = 138
OR NRO_PRE_FAT = 139
OR NRO_PRE_FAT = 140
OR NRO_PRE_FAT = 149
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 
OR NRO_PRE_FAT = 

ROLLBACK




, frt_pre_Fat
