CREATE OR REPLACE FUNCTION "FRT_GET_USU_SISTEMA" RETURN VARCHAR2
IS
VV_USU_REDE VARCHAR2(255);
BEGIN
   SELECT SYS_CONTEXT ('USERENV', 'CLIENT_INFO')OS_USER_LAN
    INTO VV_USU_REDE
    FROM DUAL;
    RETURN upper(VV_USU_REDE);
END;
